openapi: 3.0.3
info:
  title: HistoryMind AI Contract
  version: 1.0.0

paths:
  /chat:
    post:
      summary: AI reasoning endpoint
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AIChatRequest"
      responses:
        "200":
          description: AI raw response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AIChatResponse"

components:
  schemas:
    AIChatRequest:
      type: object
      required: [query]
      properties:
        query:
          type: string
          maxLength: 500

    AIChatResponse:
      type: object
      required: [answer, confidence]
      properties:
        answer:
          type: string
        confidence:
          type: number
          minimum: 0
          maximum: 1
        sources:
          type: array
          items:
            type: string
