openapi: 3.0.3
info:
  title: HistoryMind API
  version: 1.0.0

paths:
  /api/v1/chat:
    post:
      summary: Ask a historical question
      operationId: chat
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChatRequest"
      responses:
        "200":
          description: Chat response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ChatResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalError"

components:
  schemas:
    ChatRequest:
      type: object
      required: [query]
      properties:
        query:
          type: string
          maxLength: 500

    ChatResponse:
      type: object
      required: [query, answer, no_data]
      properties:
        query:
          type: string
        intent:
          type: string
          description: Intent inferred by backend
        answer:
          type: string
        events:
          type: array
          items:
            type: object
            properties:
              title:
                type: string
              year:
                type: integer
              description:
                type: string
        no_data:
          type: boolean

  responses:
    BadRequest:
      description: Invalid input
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

    InternalError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

  schemas:
    ErrorResponse:
      type: object
      required: [code, message]
      properties:
        code:
          type: string
        message:
          type: string
